# Generated by Django 5.0.1 on 2024-03-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otazky', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_text_question',
            field=models.BooleanField(default=False),
        ),
    ]
