# Generated by Django 5.0.1 on 2024-03-29 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otazky', '0003_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='course',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='otazky.course'),
        ),
    ]
