# Generated by Django 5.0.1 on 2024-03-30 16:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otazky', '0004_score_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChalangeQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('okruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otazky.course')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otazky.question')),
            ],
        ),
    ]
