# Generated by Django 5.0.1 on 2024-03-30 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otazky', '0005_chalangequestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chalangequestion',
            old_name='okruh',
            new_name='courseID',
        ),
    ]
