# Generated by Django 5.0.1 on 2024-04-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otazky', '0009_alter_course_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='full_name',
            field=models.CharField(default=models.CharField(default='', max_length=255, unique=True), max_length=255),
        ),
    ]
