# Generated by Django 5.0.1 on 2024-04-08 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otazky', '0012_alter_course_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='full_name',
        ),
    ]
