# Generated by Django 5.0.1 on 2024-10-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otazky', '0014_course_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='okruh',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='okruh',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
