# Generated by Django 5.0.1 on 2025-03-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otazky', '0017_alter_okruh_finished_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ai_context',
            field=models.CharField(default='', max_length=255),
        ),
    ]
