# Generated by Django 5.0.1 on 2025-04-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otazky', '0018_question_ai_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ai_context',
            field=models.CharField(blank='True', default='', max_length=255),
        ),
    ]
